### ISSUE TITLE
Issues running Notebook due to Tensorforce changes

### ISSUE THREAD

**Issue by dnhkng** [wassname/rl-portfolio-management#12]
Hi, 

Nice work on this project! I much prefer Jupyter to what the paper's authors have used.

I've just installed the dependencies, and have hit some errors:

`# sanity check out environment is working
state = environment.reset()
state, reward, done=environment.execute(env.action_space.sample())
state.shape`

gives me:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-15-20653d2d2786> in <module>()
>       1 # sanity check out environment is working
>       2 state = environment.reset()
> ----> 3 state, reward, done=environment.execute(env.action_space.sample())
>       4 state.shape
> 
> ~\Anaconda3\lib\site-packages\tensorforce\contrib\openai_gym.py in execute(self, actions)
>      67 
>      68     def execute(self, actions):
> ---> 69         if self.visualize:
>      70             self.gym.render()
>      71         # if the actions is not unique, that is, if the actions is a dict
> 
> AttributeError: 'TFOpenAIGymCust' object has no attribute 'visualize'

Skipping this cell and going further, I hit the next roadblock.
`from tensorforce import Configuration`

I have read on Tensorforce repo issues that the entire Configuration object has been scrapped (https://github.com/reinforceio/tensorforce/issues/132), so this breaks the current code here.

**Comment by wassname** [comment]
I included the tensorforce version I used in the requirements.txt, yeah I need to update it to the latest version

**Comment by WQtong** [comment]
Hi, have you updated the notebook? I struggled with the "Configuration" part. I tried to read the updates on tensorforce documentation but failed on exploration.

Great thanks for any updates for this project!

**Comment by wassname** [comment]
Yup the latest commit updates to to 0.3.5.2. When you run into version errors, make sure you install the right version from `requirements.txt` file.
