### ISSUE TITLE
Question about mean market performance

### ISSUE THREAD

**Issue by leahwu** [wassname/rl-portfolio-management#13]
Hi!

I was looking through your readme file and I was wondering how you calculated the "mean market performance" in the first plot to be compared to the portfolio agent performance?

**Comment by wassname** [comment]
I assume someone holds an equal amount of each asset e.g. 33% 33% 33% and plot the return on initial investment. 

The old code for it is [here](https://github.com/wassname/rl-portfolio-management/blob/c941681786bffbe968e4f4f8d3c904806d83460f/src/environments/portfolio.py#L238). It's just taking a (unweighted) mean of the return for all assets.

**Comment by leahwu** [comment]
@wassname I see. Thank you~

So what you defined seems identical to the UBAH measurement in the original paper, which is:
"the Uniform Buy and Hold (UBAH), a portfolio management approach
simply equally spreading the total fund into the preselected assets and holding them without
making any purchases or selling until the end (Li and Hoi, 2014)"

**Comment by wassname** [comment]
Yup that sounds right!
