### ISSUE TITLE
Question - Tensorflow-gpu optional?

### ISSUE THREAD

**Issue by Purdy8TV** [wassname/rl-portfolio-management#14]
Hi,

I was wanting to use your program and alter the algorithms behind it (employing reinforcement learning) and largely leave the base code untouched.

Checking 'tensorforce-PPO-IEET' I don't see tensorflow-gpu being used, is this assumption wrong? (Wanting to work on this on OSX which lost support for tfgpu at 1.1)

EDIT: Okay I've tried installing some different versions of the libraries in your requirements as I couldn't get them to install (particularly the tensorflow-gpu)

Reduced the step count significantly along with epsilon requirement.

However when I'm getting to the Test block I'm getting the following error.

```
`AttributeError                            Traceback (most recent call last)
<ipython-input-23-a605848dcb2f> in <module>()
      1 # Create an agent
      2 agent = PPOAgent(
----> 3     states_spec=environment.states,
      4     actions_spec=actions_spec,
      5     network_spec=network_spec,

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorforce/contrib/openai_gym.py in states(self)
     77     @property
     78     def states(self):
---> 79         return OpenAIGym.state_from_space(space=self.gym.observation_space)
     80 
     81     @staticmethod

AttributeError: 'NoneType' object has no attribute 'observation_space'`
```

Thank you

**Comment by wassname** [comment]
From memory I think it works without the gpu, and at about the same speed since it's bound by the speed of the environment - not the optimization.

Try installing the version from requirements/requirements.txt, otherwise you will get errors.

**Comment by Purdy8TV** [comment]
Sorry I should have been more clear it was only tensorflow-gpu (I'm just using tensor flow 1.5.0 and it doesn't appear to be causing issues) and tensorforce.

it would appear tensorforce is giving me the issue as shown above, I was able to install the specific commit in your requirements by manual install but mine still reports back as '0.3.5.1' rather than '0.3.5.2'

```

AttributeError                            Traceback (most recent call last)
<ipython-input-22-a605848dcb2f> in <module>()
      1 # Create an agent
      2 agent = PPOAgent(
----> 3     states_spec=environment.states,
      4     actions_spec=actions_spec,
      5     network_spec=network_spec,

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorforce-0.3.5.1-py3.6.egg/tensorforce/contrib/openai_gym.py in states(self)
     77     @property
     78     def states(self):
---> 79         return OpenAIGym.state_from_space(space=self.gym.observation_space)
     80 
     81     @staticmethod

AttributeError: 'NoneType' object has no attribute 'observation_space'
```
I shall try to investigate this further

**Comment by wassname** [comment]
That makes sense. Mine actually says 0.3.5.1 too, so maybe that's a typo in requirements.txt (fixed). 

Do you want to check what version of gym you have? They have refactored it recently and that could be causing the error (should be 0.9.3).

**Comment by Purdy8TV** [comment]
Yeah I've double checked my versions of everything. I'm going to get to grips with using a virtual environment and use one for this to try and figure this out instead of hassling you with basic queries.

Thanks for the replies.

**Comment by Purdy8TV** [comment]
Okay I have set up virtualenvs on both W10 and OSX and I'm reproducing the same error above on both OS.

Deviations from the requirements.txt 

- tensorflow(1.5.0) instead of tensorflow-gpu(1.3.0)
- I have to download the tensorforce link and delete the build file within it and install manually.
- [See installed modules in virtualenv](https://gist.github.com/Purdy8TV/d15810217196731473a6d7b42012ed07)

Error once again, not sure if you have anything to suggest?

```

AttributeError                            Traceback (most recent call last)
<ipython-input-22-a605848dcb2f> in <module>()
      1 # Create an agent
      2 agent = PPOAgent(
----> 3     states_spec=environment.states,
      4     actions_spec=actions_spec,
      5     network_spec=network_spec,

d:\daniel\google drive\python\envtesting\testenvw10\lib\site-packages\tensorforce-0.3.5.1-py3.6.egg\tensorforce\contrib\openai_gym.py in states(self)
     77     @property
     78     def states(self):
---> 79         return OpenAIGym.state_from_space(space=self.gym.observation_space)
     80 
     81     @staticmethod

AttributeError: 'NoneType' object has no attribute 'observation_space'


```

**Comment by wassname** [comment]
No worries, seems like it's not a basic question and you've tried all the obvious things. I'll try to replicate on my desktop when I'm at home.

For now I'm thinking try earlier/later version of gym or tensorforce. 

I've also got a DDPG pytorch notebook, which is a lot more fun (and pythonic) to debug and play with. That's my latest attemmpt. I'm not sure if you would prefer that? I can upload it for you.

**Comment by Purdy8TV** [comment]
I shall play around with earlier versions of gym or tesorforce and see where it gets me.

Thanks, I will certainly try to understand and see if I can get it working.

**Comment by Purdy8TV** [comment]
Had a brief play around with the DDPG pytorch but had a few issues.

Currently have it running as reading from one of the other questions this has a run time ~5 hours? I'm wondering if my adjustment of the steps/epsilon value could be causing issue? (Considering I can replicate it on each system) Hopefully have an update in a few hours.

**Comment by wassname** [comment]
Yeah that's about right, it takes a while

**Comment by Purdy8TV** [comment]
Do I think the DDPG one is easier to use? If so I haven't given it enough time to be honest.

I let the PPO run for it appears ~16 hours going by my command prompt saves. This was the output which it has stopped at for ~3 hours - https://gist.github.com/Purdy8TV/75dceb3f6fb5ae0910bb493f9d1ce4c8

I've been given your repo to work on as a final year project, however my course wasn't programming focused (mathematical finance) and my only python knowledge comes from a few small projects I made myself, but yes my goal is to get this working and improve upon it (granted I see you're quite active with RL so that may be difficult to achieve) but will share anything.

**Comment by wassname** [comment]
How long do you have to spend on the final project? RL can be a bit of a time sink since lots of times you run a ton of experiments and get no signal. I always used to bite off more than I can chew, but as long as you have your sights set on a few doable experiments and some nice graphs it should be fine. I'm pretty sure you can change it or change the scope if you want since it's your project.

If you want a quick intro to RL I quite liked [the deeprl bootcamp](https://sites.google.com/view/deep-rl-bootcamp/lectures), but other people prefer Silver's course because it walks you through it. I found it helped a lot working out hyper-parameters etc. Eventually you might want RL tips and there are [a bunch here on reddit](https://www.reddit.com/r/reinforcementlearning/comments/7s8px9/deep_reinforcement_learning_practical_tips/).

I would definitely try the pytorch one as I found it much easier to modify and play with compared to tensorflow based algorithms. Seems like your good at programming so I'm sure you'll work it out either way.

It'l be cool to see what you find, you should send me a copy of your write up when you get to that stage.

**Comment by wassname** [comment]
From your gist it doesn't look like it learned much because the output weights look like random noise. Or at least that's my interpretation. PPO learns a mean action and a standard deviation. One common failure case it where it leans mean=0 and std=small. This avoid most fees but, but because of the standard deviation, you see the weights change a little during training.

**Comment by Purdy8TV** [comment]
I have about 12 weeks from now and have budgeted around 250 hours roughly.

Cheers, I will take your advice and give it the time tomorrow to get it going. Also thanks for the link of resources, been using David Silver so far but happy to repeat some material to solidify my understandings. I think I need to play around with some simpler programs also.

Okay I'll need to take a closer look at that to understand why this occurred. I was under the impression it was limited to 12^6 steps but took 12,000,000.

**Comment by hmingkwan** [comment]
Hi guys, I encounter the same AttributeError, may I know that if it is fixed already?

**Comment by wassname** [comment]
I haven't had time yet sorry, hopefully this weekend

**Comment by Purdy8TV** [comment]
Hi,

Don't suppose you've experienced the following with the pytorch ddpg before - https://gist.github.com/Purdy8TV/82ea432b4cff4ad10d81829eefd53901 ?

**Comment by wassname** [comment]
Better not to mix issues on this thread, so is it alright if (in future) you make a separate issue for different problems. Or if it's code that's not up on the repo, email me instead (wassname at wassname then org)?

Looks like that was an old version of that notebook, I update [the gist](https://gist.github.com/wassname/03521b8c3fddd390a7caccd0934f1823) with a version that runs, (but testing doesn't work yet). Basically the enviroment returns a dict, but I'm not using a openai.gym.wrapper to transform the state into an array. In the notebook you just tried it was trying to slice a dict. To debug those error I find it useful to [make a new cells with `%debug`](https://ipython.org/ipython-doc/3/interactive/magics.html#magic-debug) which enters python debugging mode.

**Comment by wassname** [comment]
I had a go at replicating that AttributeError, but I couldn't. I can't see how it can be happening with the current version of the notebook. 

@Purdy8TV could you please check if you were using the latest version of the notebook (same as on the repo)? And could you also run `conda list` and `pip freeze` and show me the output?

**Comment by hmingkwan** [comment]
Hi @wassname, thanks for updating the tensorforce-PPO-IEET.ipynb, is the testing part not ready yet?

**Comment by wassname** [comment]
It's working in the latest notebook

**Comment by hmingkwan** [comment]
@wassname When I try to run the tensorforce-PPO-IEET.ipynb, there is an error AttributeError.
![screen shot 2018-02-23 at 10 12 11 am](https://user-images.githubusercontent.com/8529471/36574796-53f7e2fc-1882-11e8-94e7-d99454ab32f9.png)

**Comment by wassname** [comment]
Please make a separate issue for new issues, and provide details needed to replicate it. Make sure you have the right versions of everything and updated files from the repo.
