### ISSUE TITLE
Some problem of the torch

### ISSUE THREAD

**Issue by smileyung** [wassname/rl-portfolio-management#18]
when I type the instruction "pip install -r requirements/requirements.txt",
I get the error message:

Could not find a version that satisfies the requirement torch==0.3.0.post4 (from -r requirements/requirements.txt (line 19)) (from versions: 0.1.2, 0.1.2.post1, 0.3.1, 0.4.0)
No matching distribution found for torch==0.3.0.post4 (from -r requirements/requirements.txt (line 19))

what's wrong with it?
how can I solve it?

**Comment by wassname** [comment]
It looks like they must have removed that version from the pypi. Try editing requirements.txt to use the nearest version `torch==0.3.0.post4` => `torch==0.3.1`. Then running "pip install -r requirements/requirements.txt". That will probably work since the versions are quite close.

**Comment by smileyung** [comment]
Thanks a lot, torch==0.3.0.post4 => torch==0.3.1 work!

But there is another problem in tensorforce-PPO-IEET.ipynb

In [12]:
AttributeError: module 'tensorflow.python.layers.layers' has no attribute 'AveragePooling1D'

**Comment by wassname** [comment]
That's probably the wrong version of tensorforce, but can you post the long error? That way I can go up the stack until I see this repo's code.
