### ISSUE TITLE
Error in importing agents, utils, components

### ISSUE THREAD

**Issue by varunksj** [wassname/rl-portfolio-management#23]
In pytorch implementation of the above model, and in 10th cell. You have used following - 

*from agent import ProximalPolicyOptimization, DisjointActorCriticNet #, DeterministicActorNet, DeterministicCriticNet
from component import GaussianPolicy, HighDimActionReplay, OrnsteinUhlenbeckProcess
from utils import Config, Logger
import gym
import torch
gym.logger.setLevel(logging.INFO)*

It is giving me error that agent module does not exist which I think it should because we dont have folder with agent, component name. 
I am sorry but I am not able to understand what I am missing here. Please help. 
Thanks in advance.

**Comment by wassname** [comment]
This repo is not maintained so please read the notices at the top of the readme and consider the more up to date repos.

When you say "above model" I'm guessing you mean the DDPG notebook. Try reading it again from the top, if you followed the instructions in the first markdown cell you should have cloned a repository into the DeepRL subfolder, and then run a cell which adds it to the path (`os.sys.path.append(os.path.abspath('DeepRL'))`), enabling imports from the agent.py file.
